import 'package:cal_track_v1/models/aliment.dart';

// Portions standards pour les aliments CIQUAL
// Clé = nom exact tel qu'il apparaît dans ciqual4.csv
// Valeurs issues des références ANSES, PNNS et standards culinaires français
const Map<String, List<List<dynamic>>> _portionsData = {

  // ── Fruits entiers ────────────────────────────────────────────────────────

  'Abricot, dénoyauté, cru': [['petite', 40.0], ['moyenne', 60.0], ['grande', 80.0]],
  'Ananas, chair sans peau, cru': [['tranche', 80.0], ['demi', 400.0]],
  'Avocat, chair sans peau, sans noyau, cru': [['petit', 100.0], ['moyen', 150.0], ['grand', 200.0]],
  'Banane, chair sans peau, crue': [['petite', 80.0], ['moyenne', 100.0], ['grande', 130.0]],
  'Banane plantain, crue': [['petite', 120.0], ['grande', 180.0]],
  'Cassis, cru': [['portion', 80.0]],
  'Cerise, chair et peau, sans noyau, crue': [['portion', 80.0], ['grande portion', 120.0]],
  'Citron, chair sans peau, sans pépins, cru': [['petit', 60.0], ['moyen', 80.0]],
  'Clémentine ou mandarine, chair sans peau, sans pépins, crue': [['petite', 60.0], ['moyenne', 80.0], ['grande', 100.0]],
  'Coing, cru': [['moyen', 150.0]],
  'Figue, crue': [['petite', 40.0], ['moyenne', 60.0]],
  'Fraise, crue': [['portion', 100.0], ['grande portion', 150.0]],
  'Framboise, crue': [['portion', 80.0], ['grande portion', 120.0]],
  'Grenade, chair sans peau, avec pépins, crue': [['petite', 200.0], ['grande', 350.0]],
  'Groseille, crue': [['portion', 80.0]],
  'Griotte, crue': [['portion', 80.0], ['grande portion', 120.0]],
  'Kaki, chair et peau, cru': [['petit', 150.0], ['grand', 220.0]],
  'Kiwi, chair sans peau, avec pépins, cru': [['petit', 70.0], ['moyen', 90.0], ['grand', 110.0]],
  'Litchi, chair sans peau, sans noyau, cru': [['portion', 80.0], ['grande portion', 130.0]],
  'Mangue, chair sans peau, sans noyau, crue': [['petite', 200.0], ['grande', 400.0]],
  'Melon cantaloup (par ex.: Charentais), chair sans peau, sans pépins, cru': [['tranche', 150.0], ['demi', 400.0]],
  'Myrtille, crue': [['portion', 80.0], ['grande portion', 120.0]],
  'Mûre (de ronce), crue': [['portion', 80.0]],
  'Nectarine ou brugnon, jaune, chair et peau, sans noyau, crue': [['petite', 120.0], ['moyenne', 150.0], ['grande', 180.0]],
  'Nectarine ou brugnon, blanche, chair et peau, sans noyau, crue': [['petite', 120.0], ['moyenne', 150.0], ['grande', 180.0]],
  'Orange, chair sans peau, sans pépins, crue': [['petite', 120.0], ['moyenne', 150.0], ['grande', 200.0]],
  'Papaye, chair sans peau, crue': [['tranche', 150.0], ['demi', 300.0]],
  'Pastèque, chair sans peau, sans pépins, crue': [['tranche', 200.0], ['grande tranche', 300.0]],
  'Pêche, chair et peau, sans noyau, crue': [['petite', 120.0], ['moyenne', 150.0], ['grande', 180.0]],
  'Pêche blanche, chair et peau, sans noyau, crue': [['petite', 120.0], ['moyenne', 150.0], ['grande', 180.0]],
  'Pêche jaune, chair et peau, sans noyau, crue': [['petite', 120.0], ['moyenne', 150.0], ['grande', 180.0]],
  'Poire, chair et peau, crue': [['petite', 120.0], ['moyenne', 150.0], ['grande', 200.0]],
  'Poire Conférence, chair sans peau, crue': [['petite', 120.0], ['moyenne', 150.0], ['grande', 200.0]],
  'Poire Williams, chair sans peau, crue': [['petite', 120.0], ['moyenne', 150.0], ['grande', 200.0]],
  'Pomme, chair et peau, crue': [['petite', 130.0], ['moyenne', 160.0], ['grande', 200.0]],
  'Pomme Canada, chair sans peau, crue': [['petite', 130.0], ['moyenne', 160.0], ['grande', 200.0]],
  'Pomme Golden, chair sans peau, crue': [['petite', 130.0], ['moyenne', 160.0], ['grande', 200.0]],
  'Pomme Granny Smith, chair et peau, crue': [['petite', 130.0], ['moyenne', 160.0], ['grande', 200.0]],
  'Pomme Gala, chair sans peau, crue': [['petite', 130.0], ['moyenne', 160.0], ['grande', 200.0]],
  'Pomme Pink lady, chair sans peau, crue': [['petite', 130.0], ['moyenne', 160.0], ['grande', 200.0]],
  'Pomme Chantecler, chair sans peau, crue': [['petite', 130.0], ['moyenne', 160.0], ['grande', 200.0]],
  'Pomelo (dit Pamplemousse), chair sans peau, sans pépins, cru': [['demi', 200.0], ['entier', 400.0]],
  'Prune mirabelle, sans noyau, crue': [['portion', 80.0], ['grande portion', 130.0]],
  'Prune Reine-Claude, sans noyau, crue': [['petite', 30.0], ['moyenne', 50.0]],
  'Prune, sans noyau, crue': [['petite', 30.0], ['grande', 60.0]],
  'Raisin blanc, à gros grain (type Italia ou Dattier), cru': [['portion', 80.0], ['grande portion', 120.0]],
  'Raisin noir, cru': [['portion', 80.0], ['grande portion', 120.0]],
  'Rhubarbe, tige, crue': [['portion', 100.0]],
  'Fruit de la passion ou maracudja, chair sans peau, avec pépins, cru': [['unité', 30.0]],
  'Carambole, chair et peau, crue': [['moyen', 100.0]],
  'Gombo, fruit, cru': [['portion', 100.0]],

  // ── Fruits secs et oléagineux ─────────────────────────────────────────────

  'Abricot, dénoyauté, sec': [['portion', 30.0], ['grande portion', 50.0]],
  'Datte, chair et peau, sans noyau, sèche': [['portion', 30.0], ['grande portion', 50.0]],
  'Figue, sèche': [['portion', 30.0], ['grande portion', 50.0]],
  'Pruneau, sans noyau, sec': [['portion', 30.0], ['grande portion', 50.0]],
  'Raisin sec': [['portion', 30.0]],
  'Amande, avec peau, sans sel ajouté': [['poignée', 30.0]],
  'Amande, grillée, salée': [['poignée', 30.0]],
  'Cacahuète, sans sel ajouté': [['poignée', 30.0]],
  'Cacahuète, grillée, salée': [['poignée', 30.0]],
  'Noisette, sans sel ajouté': [['poignée', 30.0]],
  'Noix, cerneau, séchée': [['poignée', 30.0]],
  'Noix du Brésil ou noix d\'Amazonie, sans sel ajouté': [['poignée', 30.0]],
  'Pistache, grillée, salée': [['poignée', 30.0]],
  'Pistache, grillée, sans sel ajouté': [['poignée', 30.0]],
  'Noix de cajou, grillée, salée': [['poignée', 30.0]],
  'Noix de cajou, grillée, sans sel ajouté': [['poignée', 30.0]],
  'Noix de pécan, sans sel ajouté': [['poignée', 30.0]],
  'Noix de macadamia, sans sel ajouté': [['poignée', 30.0]],
  'Pignon de pin': [['portion', 15.0]],
  'Châtaigne, bouillie/cuite à l\'eau': [['portion', 80.0], ['grande portion', 150.0]],
  'Châtaigne, grillée': [['portion', 80.0], ['grande portion', 150.0]],

  // ── Légumes ───────────────────────────────────────────────────────────────

  'Artichaut, cuit': [['petit', 200.0], ['grand', 350.0]],
  'Asperge blanche, bouillie/cuite à l\'eau': [['3 asperges', 100.0], ['6 asperges', 200.0]],
  'Asperge, verte, crue': [['3 asperges', 80.0], ['6 asperges', 160.0]],
  'Aubergine, crue': [['portion', 150.0]],
  'Aubergine, cuite': [['portion', 150.0]],
  'Batavia, crue': [['portion', 80.0]],
  'Betterave rouge, cuite': [['petite', 100.0], ['moyenne', 150.0]],
  'Betterave rouge, crue': [['petite', 100.0], ['moyenne', 150.0]],
  'Brocoli, cru': [['portion', 150.0]],
  'Brocoli, bouilli/cuit à l\'eau (aliment moyen)': [['portion', 150.0]],
  'Carotte, crue': [['petite', 60.0], ['moyenne', 80.0], ['grande', 120.0]],
  'Carotte, bouillie/cuite à l\'eau (aliment moyen)': [['portion', 150.0]],
  'Céleri branche, cru': [['branche', 40.0], ['portion', 100.0]],
  'Céleri-rave, cuit': [['portion', 150.0]],
  'Champignon de Paris ou champignon de couche, cru': [['portion', 80.0], ['grande portion', 150.0]],
  'Champignon, chanterelle ou girolle, crue': [['portion', 80.0]],
  'Champignon, cèpe, cru': [['portion', 80.0]],
  'Champignon, lentin comestible ou shiitaké, cuit': [['portion', 80.0]],
  'Chou blanc, cru': [['portion', 100.0]],
  'Chou de Bruxelles, cru': [['portion', 100.0], ['grande portion', 150.0]],
  'Chou frisé, cru': [['portion', 80.0]],
  'Chou rouge, cru': [['portion', 80.0]],
  'Chou romanesco ou brocoli à pomme, cru': [['portion', 150.0]],
  'Chou vert, cuit': [['portion', 150.0]],
  'Chou-fleur, cru': [['portion', 150.0]],
  'Concombre, chair et peau, cru': [['demi', 150.0], ['entier', 300.0]],
  'Courge butternut (doubeurre), chair sans peau, crue': [['portion', 150.0]],
  'Courgette, chair et peau, crue': [['petite', 150.0], ['grande', 250.0]],
  'Courgette, chair et peau, cuite': [['portion', 150.0]],
  'Endive, crue': [['petite', 100.0], ['grande', 150.0]],
  'Épinard, cru': [['portion', 80.0]],
  'Épinard, cuit': [['portion', 150.0]],
  'Fenouil, cru': [['demi', 150.0], ['entier', 300.0]],
  'Haricot vert, cru': [['portion', 150.0]],
  'Haricot vert, cuit': [['portion', 150.0]],
  'Laitue, crue': [['portion', 80.0]],
  'Laitue romaine, crue': [['portion', 80.0]],
  'Laitue iceberg, crue': [['portion', 80.0]],
  'Mâche, crue': [['portion', 50.0]],
  'Maïs doux, en épis, cuit': [['demi-épi', 100.0], ['épi entier', 200.0]],
  'Navet, cuit': [['portion', 100.0]],
  'Oignon, cru': [['petit', 70.0], ['moyen', 100.0]],
  'Panais, cru': [['portion', 100.0]],
  'Poireau, cru': [['petit', 100.0], ['grand', 150.0]],
  'Pois mange-tout ou pois gourmand, cru': [['portion', 80.0], ['grande portion', 120.0]],
  'Poivron, vert, jaune ou rouge, cru': [['demi', 80.0], ['entier', 150.0]],
  'Poivron vert, cru': [['demi', 80.0], ['entier', 150.0]],
  'Poivron rouge, cru': [['demi', 80.0], ['entier', 150.0]],
  'Poivron jaune, cru': [['demi', 80.0], ['entier', 150.0]],
  'Potimarron, chair sans peau, cru': [['portion', 150.0]],
  'Potiron, cru': [['portion', 150.0]],
  'Radis rouge, cru': [['botte', 80.0]],
  'Roquette, crue': [['portion', 50.0]],
  'Salade feuille de chêne, crue': [['portion', 80.0]],
  'Salade sucrine, crue': [['portion', 80.0]],
  'Salsifis, cuit': [['portion', 100.0]],
  'Scarole, crue': [['portion', 80.0]],
  'Topinambour, cuit': [['portion', 150.0]],
  'Tomate cerise, crue': [['portion', 80.0], ['grande portion', 130.0]],
  'Tomate ronde, crue': [['petite', 80.0], ['moyenne', 120.0], ['grande', 180.0]],
  'Tomate grappe, crue': [['petite', 80.0], ['moyenne', 120.0], ['grande', 180.0]],
  'Tomate côtelée ou coeur de boeuf, crue': [['petite', 150.0], ['grande', 250.0]],
  'Tomate sans précision, crue (aliment moyen)': [['petite', 80.0], ['moyenne', 120.0], ['grande', 180.0]],

  // ── Légumineuses ─────────────────────────────────────────────────────────

  'Lentille, bouillie/cuite à l\'eau (aliment moyen)': [['portion', 150.0], ['grande portion', 200.0]],
  'Lentille verte, bouillie/cuite à l\'eau': [['portion', 150.0], ['grande portion', 200.0]],
  'Lentille blonde, bouillie/cuite à l\'eau': [['portion', 150.0], ['grande portion', 200.0]],
  'Lentille corail, bouillie/cuite à l\'eau': [['portion', 150.0], ['grande portion', 200.0]],
  'Haricot blanc, bouilli/cuit à l\'eau': [['portion', 150.0], ['grande portion', 200.0]],
  'Haricot blanc, appertisé, égoutté': [['portion', 150.0]],
  'Haricot rouge, bouilli/cuit à l\'eau': [['portion', 150.0], ['grande portion', 200.0]],
  'Haricot rouge, appertisé, égoutté': [['portion', 150.0]],
  'Haricot flageolet, bouilli/cuit à l\'eau': [['portion', 150.0]],
  'Haricot flageolet, vert, bouilli/cuit à l\'eau': [['portion', 150.0]],
  'Haricot flageolet, appertisé, égoutté': [['portion', 150.0]],
  'Haricot coco, bouilli/cuit à l\'eau': [['portion', 150.0]],
  'Haricot mungo, frais, bouilli/cuit à l\'eau': [['portion', 150.0]],
  'Pois cassé, bouilli/cuit à l\'eau': [['portion', 150.0], ['grande portion', 200.0]],
  'Pois chiche, bouilli/cuit à l\'eau': [['portion', 150.0], ['grande portion', 200.0]],
  'Pois chiche, appertisé, égoutté': [['portion', 150.0]],
  'Fève, bouillie/cuite à l\'eau': [['portion', 150.0]],

  // ── Féculents cuits ───────────────────────────────────────────────────────

  'Riz blanc, cuit, sans sel ajouté': [['portion', 150.0], ['grande portion', 200.0]],
  'Riz blanc étuvé, cuit, sans sel ajouté': [['portion', 150.0], ['grande portion', 200.0]],
  'Riz complet, cuit, sans sel ajouté': [['portion', 150.0], ['grande portion', 200.0]],
  'Riz thaï, cuit, sans sel ajouté': [['portion', 150.0], ['grande portion', 200.0]],
  'Riz basmati, cuit, sans sel ajouté': [['portion', 150.0], ['grande portion', 200.0]],
  'Pâtes sèches, standard, cuites, sans sel ajouté': [['portion', 180.0], ['grande portion', 250.0]],
  'Pâtes sèches, au blé complet, cuites, sans sel ajouté': [['portion', 180.0], ['grande portion', 250.0]],
  'Pâtes sèches, aux oeufs, cuites, sans sel ajouté': [['portion', 180.0], ['grande portion', 250.0]],
  'Pâtes sèches, semi-complètes, cuites, sans sel ajouté': [['portion', 180.0], ['grande portion', 250.0]],
  'Semoule ou graine de couscous, cuite, sans sel ajouté': [['portion', 180.0], ['grande portion', 250.0]],
  'Boulgour de blé, cuit, sans sel ajouté': [['portion', 180.0], ['grande portion', 250.0]],
  'Quinoa, bouilli/cuit à l\'eau, sans sel ajouté': [['portion', 150.0], ['grande portion', 200.0]],
  'Polenta ou semoule de maïs, cuite, sans sel ajouté': [['portion', 150.0]],
  'Orge perlée, bouilli/cuite à l\'eau, sans sel ajouté': [['portion', 150.0]],
  'Pomme de terre, bouillie/cuite à l\'eau': [['petite', 120.0], ['standard', 200.0], ['grande', 300.0]],
  'Pomme de terre, sans peau, rôtie/cuite au four': [['petite', 120.0], ['standard', 200.0], ['grande', 300.0]],
  'Pomme de terre, rôtie/cuite au four': [['petite', 120.0], ['standard', 200.0], ['grande', 300.0]],
  'Pomme de terre de conservation, sans peau, bouillie/cuite à l\'eau': [['petite', 120.0], ['standard', 200.0], ['grande', 300.0]],
  'Pomme de terre nouvelle ou primeur, bouillie/cuite à l\'eau': [['petite', 120.0], ['standard', 200.0], ['grande', 300.0]],
  'Patate douce, cuite': [['petite', 120.0], ['standard', 200.0], ['grande', 300.0]],

  // ── Céréales petit-déjeuner ───────────────────────────────────────────────

  'Flocons d\'avoine': [['bol', 50.0]],
  'Avoine, crue': [['bol', 50.0]],
  'Flocons d\'avoine bouillis/cuits à l\'eau': [['bol', 200.0]],

  // ── Pain et viennoiseries ─────────────────────────────────────────────────

  'Pain (aliment moyen)': [['tranche', 30.0], ['grande tranche', 50.0]],
  'Pain blanc (par ex. : baguette, boule…)': [['tranche', 30.0], ['demi-baguette', 125.0], ['baguette', 250.0]],
  'Pain de tradition française (par ex. : baguette, boule…)': [['tranche', 30.0], ['demi-baguette', 125.0], ['baguette', 250.0]],
  'Pain au levain': [['tranche', 30.0], ['grande tranche', 50.0]],
  'Pain bis (à la farine T80 ou T110)': [['tranche', 30.0], ['grande tranche', 50.0]],
  'Pain de campagne': [['tranche', 35.0], ['grande tranche', 60.0]],
  'Pain de campagne, préemballé': [['tranche', 35.0]],
  'Pain complet ou intégral (à la farine T150)': [['tranche', 30.0], ['grande tranche', 50.0]],
  'Pain complet au seigle, préemballé': [['tranche', 30.0]],
  'Pain aux céréales et/ou aux graines': [['tranche', 30.0], ['grande tranche', 50.0]],
  'Pain aux céréales et/ou aux graines, préemballé': [['tranche', 30.0]],
  'Pain de mie blanc, préemballé': [['tranche', 25.0], ['double tranche', 50.0]],
  'Pain de mie complet, préemballé': [['tranche', 25.0], ['double tranche', 50.0]],
  'Pain de mie brioché, préemballé': [['tranche', 25.0], ['double tranche', 50.0]],
  'Pain de mie blanc, sans croûte, préemballé': [['tranche', 25.0]],
  'Pain de mie complet, sans croûte, préemballé': [['tranche', 25.0]],
  'Pain de mie aux céréales et/ou graines, préemballé': [['tranche', 25.0]],
  'Pain de seigle et froment': [['tranche', 30.0], ['grande tranche', 50.0]],
  'Pain pita': [['unité', 60.0]],
  'Pain brioché ou viennois, artisanal': [['tranche', 40.0]],
  'Pain aux céréales et/ou graines sans gluten, préemballé': [['tranche', 30.0]],
  'Pain panini': [['unité', 80.0]],
  'Muffin anglais complet, petit pain spécial, préemballé': [['unité', 65.0]],

  // ── Œufs ──────────────────────────────────────────────────────────────────

  'Oeuf cru': [['petit', 45.0], ['moyen', 55.0], ['grand', 65.0]],
  'Oeuf dur': [['petit', 45.0], ['moyen', 55.0], ['grand', 65.0]],
  'Oeuf à la coque': [['petit', 45.0], ['moyen', 55.0], ['grand', 65.0]],
  'Oeuf poché': [['petit', 45.0], ['moyen', 55.0], ['grand', 65.0]],
  'Oeuf au plat, sans matière grasse': [['unité', 55.0]],
  'Oeuf brouillé, avec matière grasse': [['unité', 55.0], ['double', 110.0]],
  'Oeuf de caille, cru': [['unité', 10.0], ['3 oeufs', 30.0]],

  // ── Produits laitiers ─────────────────────────────────────────────────────

  'Lait entier (aliment moyen)': [['verre', 200.0], ['grand verre', 250.0]],
  'Lait demi-écrémé (aliment moyen)': [['verre', 200.0], ['grand verre', 250.0]],
  'Lait écrémé, UHT': [['verre', 200.0], ['grand verre', 250.0]],
  'Lait demi-écrémé, UHT': [['verre', 200.0], ['grand verre', 250.0]],
  'Lait entier, UHT': [['verre', 200.0], ['grand verre', 250.0]],
  'Lait de chèvre, entier, UHT': [['verre', 200.0], ['grand verre', 250.0]],
  'Lait de brebis, entier': [['verre', 200.0]],
  'Yaourt ou lait fermenté, nature': [['pot', 125.0]],
  'Yaourt ou lait fermenté, nature, 0% MG': [['pot', 125.0]],
  'Yaourt ou lait fermenté, nature, 0% MG, enrichi en vitamine D': [['pot', 125.0]],
  'Yaourt ou lait fermenté, nature, à la crème': [['pot', 125.0]],
  'Yaourt ou lait fermenté, aux fruits, sucré': [['pot', 125.0]],
  'Yaourt ou lait fermenté, aromatisé, sucré': [['pot', 125.0]],
  'Yaourt ou lait fermenté, sur lit de fruits, sucré': [['pot', 125.0]],
  'Yaourt ou lait fermenté, nature, sucré': [['pot', 125.0]],
  'Yaourt à la grecque nature': [['pot', 125.0]],
  'Yaourt à la grecque nature, au lait de brebis': [['pot', 125.0]],
  'Yaourt au lait de chèvre, nature': [['pot', 125.0]],
  'Fromage blanc, nature, 0% MG': [['pot', 100.0], ['grand pot', 150.0]],
  'Fromage blanc, nature, 2-3% MG': [['pot', 100.0], ['grand pot', 150.0]],
  'Fromage blanc, nature, 7-8% MG': [['pot', 100.0], ['grand pot', 150.0]],
  'Fromage blanc, nature ou aux fruits (aliment moyen)': [['pot', 100.0], ['grand pot', 150.0]],
  'Fromage frais type petit suisse, nature, 4% MG environ': [['unité', 60.0]],
  'Fromage frais type petit suisse, nature, 0% MG': [['unité', 60.0]],
  'Fromage frais type petit suisse, nature, 10% MG environ': [['unité', 60.0]],
  'Crème 30% MG, épaisse, rayon frais': [['cuillère à soupe', 30.0]],
  'Crème 30% MG, fluide, UHT': [['cuillère à soupe', 30.0]],
  'Mascarpone': [['cuillère à soupe', 30.0], ['portion', 50.0]],
  'Ricotta': [['portion', 100.0], ['grande portion', 150.0]],
  'Burrata': [['petite', 100.0], ['standard', 125.0]],
  'Mozzarella au lait de vache': [['petite', 100.0], ['standard', 125.0]],
  'Mozzarella au lait de bufflonne ou buflesse ("di bufala")': [['petite', 100.0], ['standard', 125.0]],
  'Faisselle, 6% MG environ': [['pot', 100.0]],
  'Kéfir de lait': [['verre', 200.0]],

  // ── Fromages ──────────────────────────────────────────────────────────────

  'Camembert, sans précision sur le type de lait (pasteurisé ou cru)': [['portion', 30.0], ['quart', 65.0]],
  'Camembert au lait cru ou thermisé': [['portion', 30.0], ['quart', 65.0]],
  'Camembert au lait pasteurisé': [['portion', 30.0], ['quart', 65.0]],
  'Brie, sans précision': [['tranche', 30.0]],
  'Brie de Meaux': [['tranche', 30.0]],
  'Brie de Melun': [['tranche', 30.0]],
  'Coulommiers': [['portion', 30.0], ['quart', 65.0]],
  'Reblochon': [['portion', 30.0], ['demi', 250.0]],
  'Maroilles, laitier': [['portion', 30.0]],
  'Maroilles, fermier': [['portion', 30.0]],
  'Munster': [['portion', 30.0], ['quart', 65.0]],
  'Époisses': [['portion', 30.0], ['quart', 65.0]],
  'Livarot': [['portion', 30.0]],
  'Pont l\'Évêque': [['portion', 30.0], ['quart', 65.0]],
  'Neufchâtel': [['portion', 30.0], ['quart', 65.0]],
  'Chaource': [['portion', 30.0], ['quart', 65.0]],
  'Langres': [['portion', 30.0]],
  'Carré de l\'Est': [['portion', 30.0]],
  'Saint-Marcellin': [['entier', 80.0], ['demi', 40.0]],
  'Emmental ou emmenthal': [['tranche', 20.0], ['grande tranche', 30.0]],
  'Emmental ou emmenthal, râpé': [['portion', 30.0]],
  'Beaufort': [['tranche', 30.0]],
  'Comté': [['tranche', 20.0], ['grande tranche', 30.0]],
  'Parmesan': [['râpé', 15.0], ['portion', 30.0]],
  'Cantal': [['tranche', 30.0]],
  'Cantal jeune': [['tranche', 30.0]],
  'Cheddar': [['tranche', 25.0]],
  'Edam': [['tranche', 25.0]],
  'Gouda': [['tranche', 30.0]],
  'Mimolette jeune (moins de 6 mois d\'affinage)': [['tranche', 25.0]],
  'Raclette (fromage)': [['tranche', 30.0], ['portion', 80.0]],
  'Roquefort (fromage de brebis)': [['portion', 30.0]],
  'Fourme d\'Ambert': [['portion', 30.0]],
  'Saint-Nectaire, laitier': [['portion', 30.0]],
  'Tomme ou tome de vache': [['tranche', 30.0]],
  'Tomme ou tome de Savoie': [['tranche', 30.0]],
  'Morbier': [['tranche', 30.0]],
  'Abondance': [['tranche', 30.0]],
  'Ossau-Iraty (fromage de brebis)': [['tranche', 30.0]],
  'Feta, au lait de brebis 70% minimum et lait de chèvre 30% maximum': [['portion', 30.0], ['dés', 50.0]],
  'Fromage type feta, au lait de brebis 100%': [['portion', 30.0], ['dés', 50.0]],
  'Fromage de chèvre lactique affiné, type palet, crottin ou bûchette': [['unité', 60.0], ['demi', 30.0]],
  'Fromage de chèvre frais, type palet, crottin ou bûchette': [['unité', 60.0], ['demi', 30.0]],
  'Crottin de chèvre, sans précision sur le type de lait - pasteurisé ou cru -': [['unité', 60.0]],
  'Crottin de Chavignol (fromage de chèvre)': [['unité', 60.0]],
  'Rocamadour (fromage de chèvre)': [['unité', 35.0]],
  'Sainte-Maure de Touraine (fromage de chèvre)': [['tranche', 30.0], ['portion', 80.0]],
  'Fromage fondu en tranchettes': [['tranche', 20.0], ['double tranche', 40.0]],
  'Fromage fondu en portion (triangle), non enrichi': [['portion', 17.0], ['double', 34.0]],
  'Cancoillotte (spécialité fromagère fondue)': [['portion', 30.0]],
  'Fromage frais ou spécialité fromagère non affinée, nature, à tartiner, en barquette, non allégée en matière grasse': [['portion', 30.0]],
  'Fromage frais ou spécialité fromagère non affinée, ail et fines herbes, à tartiner, non allégée en matière grasse': [['portion', 30.0]],

  // ── Viandes bovines ───────────────────────────────────────────────────────

  'Boeuf, steak haché 5% MG cuit': [['petit', 80.0], ['standard', 120.0], ['grand', 150.0]],
  'Boeuf, steak haché 10% MG cuit': [['petit', 80.0], ['standard', 120.0], ['grand', 150.0]],
  'Boeuf, steak haché 15% MG cuit': [['petit', 80.0], ['standard', 120.0], ['grand', 150.0]],
  'Boeuf, steak haché 20% MG cuit': [['petit', 80.0], ['standard', 120.0], ['grand', 150.0]],
  'Boeuf, steak haché, cuit (aliment moyen)': [['petit', 80.0], ['standard', 120.0], ['grand', 150.0]],
  'Boeuf, steak ou bifteck grillé/poêlé': [['petit', 80.0], ['standard', 120.0], ['grand', 150.0]],
  'Boeuf, entrecôte, partie maigre grillée/poêlée': [['petit', 100.0], ['standard', 150.0], ['grand', 200.0]],
  'Boeuf, faux-filet grillé/poêlé': [['petit', 100.0], ['standard', 150.0], ['grand', 200.0]],
  'Boeuf, faux-filet rôti/cuit au four': [['petit', 100.0], ['standard', 150.0], ['grand', 200.0]],
  'Boeuf, rumsteck grillé/poêlé': [['petit', 100.0], ['standard', 150.0], ['grand', 200.0]],
  'Boeuf, tende de tranche grillée/poêlée': [['petit', 100.0], ['standard', 150.0]],
  'Boeuf, tende de tranche rôtie/cuite au four': [['petit', 100.0], ['standard', 150.0]],
  'Boeuf, rosbif rôti/cuit au four': [['tranche', 80.0], ['portion', 150.0]],
  'Boeuf, bavette d\'aloyau grillée/poêlée': [['petit', 100.0], ['standard', 150.0]],
  'Boeuf, onglet grillé/poêlé': [['petit', 100.0], ['standard', 150.0]],
  'Boeuf, hampe grillée/poêlée': [['petit', 100.0], ['standard', 150.0]],
  'Boeuf braisé': [['portion', 120.0], ['grande portion', 180.0]],
  'Boeuf, à bourguignon ou pot-au-feu, cuit': [['portion', 120.0], ['grande portion', 180.0]],
  'Boeuf, gîte à la noix cuit': [['portion', 120.0]],
  'Boeuf, joue, braisée ou bouillie/cuite à l\'eau': [['portion', 120.0]],
  'Boeuf, plat de côtes braisé ou bouilli/cuit à l\'eau': [['portion', 120.0]],
  'Veau, escalope cuite': [['petite', 80.0], ['standard', 120.0], ['grande', 150.0]],
  'Veau, noix grillée/poêlée': [['petite', 80.0], ['standard', 120.0]],
  'Veau, noix rôtie/cuite au four': [['petite', 80.0], ['standard', 120.0]],
  'Veau, côte grillée/poêlée': [['petite', 100.0], ['standard', 150.0]],
  'Veau, rôti cuit': [['tranche', 80.0], ['portion', 150.0]],
  'Veau, épaule grillée/poêlée': [['portion', 120.0]],
  'Veau, jarret braisé ou bouilli': [['portion', 200.0]],
  'Veau, viande, cuite (aliment moyen)': [['portion', 120.0]],
  'Cheval, steak ou bifteck cru': [['standard', 120.0]],
  'Cheval, tende de tranche grillée/poêlée': [['standard', 120.0]],
  'Cheval, faux-filet grillé/poêlé': [['standard', 120.0]],

  // ── Viandes ovines ────────────────────────────────────────────────────────

  'Agneau, gigot rôti/cuit au four': [['tranche', 80.0], ['portion', 150.0]],
  'Agneau, côtelette grillée/poêlée': [['petite', 80.0], ['standard', 100.0]],
  'Agneau, épaule rôtie/cuite au four': [['portion', 120.0]],
  'Agneau, côte filet grillée/poêlée': [['petite', 80.0], ['standard', 100.0]],
  'Agneau, selle, partie maigre rôtie/cuite au four': [['portion', 120.0]],
  'Agneau, gigot grillé/poêlé': [['portion', 120.0]],
  'Mouton, gigot rôti/cuit au four': [['portion', 120.0]],

  // ── Viandes porcines ──────────────────────────────────────────────────────

  'Porc, côte grillée/poêlée': [['petite', 120.0], ['standard', 180.0], ['grande', 220.0]],
  'Porc, filet mignon cuit': [['petit', 120.0], ['standard', 160.0]],
  'Porc, filet maigre, en rôti, cuit': [['tranche', 80.0], ['portion', 150.0]],
  'Porc, rôti cuit': [['tranche', 80.0], ['portion', 150.0]],
  'Porc, épaule cuite': [['portion', 120.0]],
  'Porc, carré cuit': [['portion', 120.0]],
  'Porc, rouelle de jambon cuite': [['portion', 150.0]],

  // ── Volailles ─────────────────────────────────────────────────────────────

  'Poulet, filet sans peau grillé/poêlé': [['petit', 100.0], ['standard', 140.0], ['grand', 180.0]],
  'Poulet, viande et peau rôties/cuites au four': [['portion', 150.0], ['grande portion', 250.0]],
  'Poulet, cuisse, viande et peau rôtie/cuite au four': [['petite', 150.0], ['grande', 250.0]],
  'Poulet, cuisse, viande rôtie/cuite au four': [['petite', 120.0], ['grande', 200.0]],
  'Poulet, cuisse, viande et peau bouillie/cuite à l\'eau': [['petite', 150.0], ['grande', 250.0]],
  'Dinde, escalope grillée/poêlée': [['petit', 100.0], ['standard', 140.0], ['grand', 180.0]],
  'Dinde, escalope rôtie/cuite au four': [['petit', 100.0], ['standard', 140.0]],
  'Dinde, viande rôtie/cuite au four': [['tranche', 80.0], ['portion', 150.0]],
  'Canard, magret grillé/poêlé': [['petit', 120.0], ['standard', 180.0]],
  'Canard, viande rôtie/cuite au four': [['portion', 120.0], ['grande portion', 180.0]],
  'Lapin, viande braisée': [['portion', 150.0], ['grande portion', 200.0]],
  'Lapin, viande cuite': [['portion', 150.0]],

  // ── Gibier ────────────────────────────────────────────────────────────────

  'Chevreuil, viande rôtie/cuite au four': [['portion', 120.0], ['grande portion', 180.0]],
  'Sanglier, viande rôtie/cuite au four': [['portion', 120.0], ['grande portion', 180.0]],
  'Cerf, viande rôtie/cuite au four': [['portion', 120.0], ['grande portion', 180.0]],

  // ── Poissons ──────────────────────────────────────────────────────────────

  'Saumon, élevage, cru': [['pavé', 120.0], ['grande portion', 180.0]],
  'Saumon, cuit, sans précision (aliment moyen)': [['pavé', 120.0], ['grande portion', 180.0]],
  'Saumon, cuit à la vapeur': [['pavé', 120.0], ['grande portion', 180.0]],
  'Saumon, grillé/poêlé': [['pavé', 120.0], ['grande portion', 180.0]],
  'Saumon, élevage, rôti/cuit au four': [['pavé', 120.0], ['grande portion', 180.0]],
  'Saumon fumé': [['tranche', 30.0], ['assiette', 80.0]],
  'Saumon, sauvage, fumé': [['tranche', 30.0], ['assiette', 80.0]],
  'Cabillaud, cru': [['filet', 120.0], ['grande portion', 180.0]],
  'Cabillaud, cuit à la vapeur': [['filet', 120.0], ['grande portion', 180.0]],
  'Cabillaud, rôti/cuit au four': [['filet', 120.0], ['grande portion', 180.0]],
  'Merlu, cru': [['filet', 120.0], ['grande portion', 180.0]],
  'Merlu, cuit à l\'étouffée': [['filet', 120.0], ['grande portion', 180.0]],
  'Thon, au naturel, appertisé, égoutté': [['petite boîte', 120.0], ['grande boîte', 200.0]],
  'Thon albacore, cru': [['portion', 120.0], ['grande portion', 180.0]],
  'Thon rouge, cru': [['portion', 120.0], ['grande portion', 180.0]],
  'Sardine, à l\'huile, appertisée, égouttée': [['petite boîte', 90.0], ['grande boîte', 135.0]],
  'Sardine, crue': [['portion', 100.0], ['grande portion', 150.0]],
  'Sardine, grillée/poêlée': [['portion', 100.0], ['grande portion', 150.0]],
  'Maquereau, rôti/cuit au four': [['filet', 120.0], ['grande portion', 180.0]],
  'Maquereau, filet (grillé ou non), au naturel, appertisé, égoutté': [['petite boîte', 120.0], ['grande boîte', 176.0]],
  'Maquereau, fumé': [['filet', 100.0], ['grande portion', 150.0]],
  'Hareng, grillé/poêlé': [['filet', 100.0], ['grande portion', 150.0]],
  'Hareng fumé, doux': [['filet', 80.0]],
  'Bar commun ou loup, rôti/cuit au four': [['filet', 120.0], ['grande portion', 180.0]],
  'Dorade royale ou daurade ou vraie daurade, rôtie/cuite au four': [['filet', 120.0], ['grande portion', 180.0]],
  'Dorade royale ou daurade ou vraie daurade, sauvage, crue': [['filet', 120.0], ['grande portion', 180.0]],
  'Sole, cuite à la vapeur': [['filet', 120.0], ['grande portion', 180.0]],
  'Sole, rôtie/cuite au four': [['filet', 120.0], ['grande portion', 180.0]],
  'Truite, rôtie/cuite au four': [['petite', 120.0], ['grande', 200.0]],
  'Truite arc en ciel, élevage, rôtie/cuite au four': [['petite', 120.0], ['grande', 200.0]],
  'Lieu noir, cuit': [['filet', 120.0], ['grande portion', 180.0]],
  'Lieu jaune ou colin, cuit': [['filet', 120.0], ['grande portion', 180.0]],
  'Haddock (fumé) ou églefin fumé': [['filet', 120.0], ['grande portion', 180.0]],
  'Lotte ou baudroie, grillée/poêlée': [['portion', 120.0], ['grande portion', 180.0]],
  'Espadon, rôti/cuit au four': [['portion', 120.0], ['grande portion', 180.0]],
  'Rouget-barbet de roche, vapeur': [['portion', 100.0], ['grande portion', 150.0]],
  'Merlan, cuit à la vapeur': [['filet', 120.0]],
  'Limande-sole, cuite à la vapeur': [['filet', 120.0]],
  'Raie, rôtie/cuite au four': [['portion', 120.0]],
  'Turbot, rôti/cuit au four': [['portion', 120.0]],
  'Anguille, rôtie/cuite au four': [['portion', 100.0], ['grande portion', 150.0]],

  // ── Fruits de mer et crustacés ────────────────────────────────────────────

  'Crevette, cuite': [['portion', 80.0], ['grande portion', 150.0]],
  'Crevette grise, cuite': [['portion', 80.0]],
  'Crevette bouquet, sauvage, cuite': [['portion', 80.0], ['grande portion', 150.0]],
  'Crevette blanche ou crevette tropicale (rose), élevage, cuite': [['portion', 80.0], ['grande portion', 150.0]],
  'Homard, bouilli/cuit à l\'eau': [['portion', 200.0], ['demi', 400.0]],
  'Langouste, bouillie/cuite à l\'eau': [['portion', 200.0]],
  'Langoustine, bouillie/cuite à l\'eau': [['portion', 100.0], ['grande portion', 150.0]],
  'Coquille Saint-Jacques, noix et corail, cuite': [['3 noix', 60.0], ['6 noix', 120.0]],
  'Moule, bouillie/cuite à l\'eau': [['portion', 150.0], ['grande portion', 250.0]],
  'Huître creuse, crue': [['3 huîtres', 75.0], ['6 huîtres', 150.0], ['douzaine', 300.0]],
  'Huître plate, crue': [['3 huîtres', 75.0], ['6 huîtres', 150.0], ['douzaine', 300.0]],
  'Crabe ou tourteau, bouilli/cuit à l\'eau': [['portion', 100.0], ['grande portion', 200.0]],
  'Calmar ou calamar ou encornet, bouilli/cuit à l\'eau': [['portion', 100.0], ['grande portion', 150.0]],
  'Poulpe, cuit': [['portion', 100.0], ['grande portion', 150.0]],
  'Escargot, cuit': [['6 escargots', 60.0], ['douzaine', 120.0]],
  'Bulot ou buccin, cuit': [['portion', 100.0]],
  'Bigorneau, cuit': [['portion', 80.0]],
  'Clam, praire ou palourde, bouilli/cuit à l\'eau': [['portion', 100.0]],

  // ── Charcuteries ──────────────────────────────────────────────────────────

  'Jambon cuit, supérieur': [['tranche', 30.0], ['double tranche', 60.0]],
  'Jambon cuit, supérieur, avec couenne': [['tranche', 30.0], ['double tranche', 60.0]],
  'Jambon cuit, supérieur, découenné': [['tranche', 30.0], ['double tranche', 60.0]],
  'Jambon cuit, choix': [['tranche', 30.0], ['double tranche', 60.0]],
  'Jambon cuit, standard': [['tranche', 30.0], ['double tranche', 60.0]],
  'Jambon de poulet ou blanc de poulet en tranche': [['tranche', 30.0], ['double tranche', 60.0]],
  'Jambon de dinde ou blanc de dinde en tranche': [['tranche', 30.0], ['double tranche', 60.0]],
  'Jambon sec': [['tranche', 20.0], ['double tranche', 40.0]],
  'Jambon de Bayonne': [['tranche', 20.0], ['double tranche', 40.0]],
  'Jambon sec de Parme': [['tranche', 20.0], ['double tranche', 40.0]],
  'Jambon sec Serrano': [['tranche', 20.0], ['double tranche', 40.0]],
  'Saucisson sec': [['tranche', 15.0], ['portion', 30.0]],
  'Saucisson sec pur porc': [['tranche', 15.0], ['portion', 30.0]],
  'Rosette ou fuseau': [['tranche', 15.0], ['portion', 30.0]],
  'Chorizo': [['tranche', 15.0], ['portion', 30.0]],
  'Chorizo supérieur, doux ou fort, type charcuterie en tranches': [['tranche', 15.0], ['portion', 30.0]],
  'Salami': [['tranche', 15.0], ['portion', 30.0]],
  'Salami pur porc': [['tranche', 15.0], ['portion', 30.0]],
  'Mortadelle': [['tranche', 20.0], ['portion', 40.0]],
  'Mortadelle pistachée pur porc': [['tranche', 20.0], ['portion', 40.0]],
  'Saucisse de Francfort': [['unité', 50.0], ['portion', 100.0]],
  'Saucisse de Strasbourg ou knack, à cuire': [['unité', 50.0], ['portion', 100.0]],
  'Chipolata cuite': [['unité', 40.0], ['portion', 120.0]],
  'Saucisse de Toulouse cuite': [['unité', 80.0], ['portion', 150.0]],
  'Merguez crue': [['unité', 70.0], ['portion', 140.0]],
  'Andouille': [['tranche', 30.0], ['portion', 80.0]],
  'Andouillette, grillée/poêlée': [['unité', 150.0]],
  'Boudin noir, grillé/poêlé': [['portion', 100.0], ['grande portion', 150.0]],
  'Boudin blanc, grillé/poêlé': [['unité', 80.0], ['grande', 120.0]],
  'Saucisson à l\'ail': [['tranche', 15.0], ['portion', 30.0]],
  'Saucisse de Morteau bouillie/cuite à l\'eau': [['tranche', 50.0], ['portion', 100.0]],
  'Filet de bacon': [['tranche', 15.0], ['double tranche', 30.0]],
  'Bresaola': [['tranche', 15.0], ['portion', 30.0]],
  'Viande des Grisons': [['tranche', 15.0], ['portion', 30.0]],
  'Coppa': [['tranche', 15.0], ['portion', 30.0]],
  'Pancetta ou poitrine roulée sèche': [['tranche', 20.0]],

};

/// Retourne les portions standards pour un aliment CIQUAL donné.
/// Retourne une liste vide si aucune portion n'est définie pour cet aliment.
List<Portion> portionsPourAliment(String nom) {
  final data = _portionsData[nom];
  if (data == null) return const [];
  return data
      .map((p) => Portion(nom: p[0] as String, poids: (p[1] as num).toDouble()))
      .toList();
}
