// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDy4X8GcZaoARiPcsjKN9oV_ej3TVes330',
    appId: '1:474981035295:web:8b5139387415cb5303142a',
    messagingSenderId: '474981035295',
    projectId: 'cal-track-55d37',
    authDomain: 'cal-track-55d37.firebaseapp.com',
    storageBucket: 'cal-track-55d37.firebasestorage.app',
    measurementId: 'G-L80SHTQQPD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB15SBhbqw1HHMq7h70uRRenzMSvRI761U',
    appId: '1:474981035295:android:d7d5a6651bcf9de703142a',
    messagingSenderId: '474981035295',
    projectId: 'cal-track-55d37',
    storageBucket: 'cal-track-55d37.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdUdgSzwh_plJL80nLQZFgLbMa2PKbyS4',
    appId: '1:474981035295:ios:bd0a4219cf037d1703142a',
    messagingSenderId: '474981035295',
    projectId: 'cal-track-55d37',
    storageBucket: 'cal-track-55d37.firebasestorage.app',
    iosBundleId: 'com.example.calTrackV1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdUdgSzwh_plJL80nLQZFgLbMa2PKbyS4',
    appId: '1:474981035295:ios:bd0a4219cf037d1703142a',
    messagingSenderId: '474981035295',
    projectId: 'cal-track-55d37',
    storageBucket: 'cal-track-55d37.firebasestorage.app',
    iosBundleId: 'com.example.calTrackV1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDy4X8GcZaoARiPcsjKN9oV_ej3TVes330',
    appId: '1:474981035295:web:20c1637433e6342003142a',
    messagingSenderId: '474981035295',
    projectId: 'cal-track-55d37',
    authDomain: 'cal-track-55d37.firebaseapp.com',
    storageBucket: 'cal-track-55d37.firebasestorage.app',
    measurementId: 'G-TVR46CBRJ6',
  );
}
